# Generated by Django 4.2.28 on 2026-02-06 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, null=True)),
                ('to_status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reservation_status_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝'), ('cancelled', '已取消'), ('expired', '已过期')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['date', 'status'], name='reservation_date_9c848d_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user', 'date'], name='reservation_user_id_3b6a90_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['classroom', 'date'], name='reservation_classro_8c2528_idx'),
        ),
        migrations.AddField(
            model_name='reservationstatuslog',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_status_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservationstatuslog',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='reservations.reservation'),
        ),
    ]
