# Generated by Django 4.2.26 on 2025-12-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_backend_registered_adminrequest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdminRequest",
        ),
    ]
