# Generated by Django 4.2 on 2025-11-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="教室名称"
                    ),
                ),
                ("building", models.CharField(max_length=50, verbose_name="楼栋")),
                ("floor", models.IntegerField(verbose_name="楼层")),
                ("room_number", models.CharField(max_length=20, verbose_name="房间号")),
                ("capacity", models.IntegerField(verbose_name="容量")),
                (
                    "classroom_type",
                    models.CharField(
                        choices=[
                            ("lecture", "普通教室"),
                            ("lab", "实验室"),
                            ("multimedia", "多媒体教室"),
                            ("conference", "会议室"),
                        ],
                        max_length=20,
                        verbose_name="教室类型",
                    ),
                ),
                (
                    "has_projector",
                    models.BooleanField(default=False, verbose_name="投影仪"),
                ),
                (
                    "has_computer",
                    models.BooleanField(default=False, verbose_name="电脑"),
                ),
                (
                    "has_microphone",
                    models.BooleanField(default=False, verbose_name="麦克风"),
                ),
                (
                    "has_whiteboard",
                    models.BooleanField(default=False, verbose_name="白板"),
                ),
                (
                    "has_air_conditioning",
                    models.BooleanField(default=False, verbose_name="空调"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="是否可用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "教室",
                "verbose_name_plural": "教室",
                "db_table": "classrooms",
                "ordering": ["building", "floor", "room_number"],
            },
        ),
    ]
