# Generated by Django 4.2.26 on 2025-12-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="classroom_type",
            field=models.CharField(
                choices=[
                    ("lecture", "普通教室"),
                    ("lab", "实验室"),
                    ("multimedia", "多媒体教室"),
                    ("conference", "会议室"),
                    ("art", "艺术室"),
                ],
                max_length=20,
                verbose_name="教室类型",
            ),
        ),
    ]
