# Generated by Django 4.2.28 on 2026-02-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_alter_classroom_classroom_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='设备名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='设备描述')),
            ],
            options={
                'verbose_name': '教室设备定义',
                'verbose_name_plural': '教室设备定义',
                'db_table': 'classroom_equipments',
            },
        ),
        migrations.CreateModel(
            name='ClassroomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='类型名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='类型描述')),
            ],
            options={
                'verbose_name': '教室类型定义',
                'verbose_name_plural': '教室类型定义',
                'db_table': 'classroom_types',
            },
        ),
    ]
