# Generated by Django 4.2.28 on 2026-02-06 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0003_classroomequipment_classroomtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReservationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_reservations', models.IntegerField(default=0)),
                ('approved_count', models.IntegerField(default=0)),
                ('rejected_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'daily_reservation_summary',
            },
        ),
        migrations.CreateModel(
            name='ClassroomUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours_used', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('reservation_count', models.IntegerField(default=0)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to='classrooms.classroom')),
            ],
            options={
                'db_table': 'classroom_usage_stats',
                'unique_together': {('classroom', 'date')},
            },
        ),
    ]
