# Generated by Django 4.2 on 2025-11-13 16:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name="内容"),
        ),
    ]
